admin_dashboard_homepage:
    path:     /
    defaults: { _controller: ActedLegalDocsBundle:Admin:index }
    methods:  GET

admin_dashboard_recommend:
    path:     /recommend/{page}
    defaults: { _controller: ActedLegalDocsBundle:Admin:recommend, page: 1 }
    methods:  GET

admin_dashboard_spotlight:
    path:     /spotlight/{page}
    defaults: { _controller: ActedLegalDocsBundle:Admin:spotlight, page: 1 }
    methods:  GET

admin_manage_recommend:
    path:     /manage_recommend
    defaults: { _controller: ActedLegalDocsBundle:Admin:changeRecommendValue, _format: json }
    methods:  POST

admin_manage_spotlight:
    path:     /manage_spotlight/{id}
    defaults: { _controller: ActedLegalDocsBundle:Admin:changeSpotlightValue, _format: json }
    methods:  POST

admin_users_list:
    path:     /users/list/{page}
    defaults: { _controller: ActedLegalDocsBundle:Admin:userList, page: 1 }
    methods:  GET

admin_create_user:
    path:     /users/create
    defaults: { _controller: ActedLegalDocsBundle:Admin:createNewUser, _format: json }
    methods:  POST

admin_resend_confirmation_token:
    path:     /users/resend_confirmation_token/{userId}
    defaults: { _controller: ActedLegalDocsBundle:Admin:resendConfirmationToken, _format: json }
    methods:  POST

admin_delete_user:
    path:     /users/delete/{user}
    defaults: { _controller: ActedLegalDocsBundle:Admin:deleteUser, _format: json }
    methods:  DELETE

admin_change_status_user:
    path:     /users/change_status/{user}
    defaults: { _controller: ActedLegalDocsBundle:Admin:changeStatus, _format: json }
    methods:  POST
