chat_room_list:
    path:     /requires/{userId}
    defaults: { _controller: ActedLegalDocsBundle:ChatRoom:getChatRoomList }
    methods:  GET

chat_room_item:
    path:     /chat/{chat}
    defaults: { _controller: ActedLegalDocsBundle:ChatRoom:getChat }
    methods:  GET

chat_room_message:
    path:     /message/{message}
    defaults: { _controller: ActedLegalDocsBundle:ChatRoom:getMessage }
    methods:  GET


