create_event:
    path:     /create
    defaults: { _controller: ActedLegalDocsBundle:Events:createEvent, _format: json }
    methods:  POST

get_events_type:
    path:     /list_events_type
    defaults: { _controller: ActedLegalDocsBundle:Events:getListEventsType, _format: json }
    methods:  GET

get_events_by_user_id:
    path:     /user_events
    defaults: { _controller: ActedLegalDocsBundle:Events:getEventsByUserId, _format: json }
    methods:  GET