create_event:
    path:     /create
    defaults: { _controller: ActedLegalDocsBundle:Events:addEvent, _format: json }
    methods:  [POST]

get_events_type:
    path:     /list_events_type
    defaults: { _controller: ActedLegalDocsBundle:Events:getListEventsType, _format: json }
    methods:  GET

get_venue_type:
    path:     /list_venue_type
    defaults: { _controller: ActedLegalDocsBundle:Events:getListVenueType, _format: json }
    methods:  GET

get_events_by_user_id:
    path:     /user_events
    defaults: { _controller: ActedLegalDocsBundle:Events:getEventsByUserId, _format: json }
    methods:  GET

get_event_by_id:
    path:     /user_events/{id}
    defaults: { _controller: ActedLegalDocsBundle:Events:getEventById, _format: json }
    methods:  POST

reject_offer:
    path: /change_status/reject/{id}
    defaults: { _controller: ActedLegalDocsBundle:Events:changeStatusToReject, _format: json }
    methods: GET

check_exist_offer:
    path: /check_exist_offer
    defaults: { _controller: ActedLegalDocsBundle:Events:checkExistOffer, _format: json }
    methods: POST

event_artists:
    path: /artists/{event}/{page}/{size}
    requirements:
      page: \d+
      size: \d+
    defaults: { _controller: ActedLegalDocsBundle:Events:getEventArtists, page: 1, size: 10 }
    methods:  GET