feedback_feedback_rating:
    path: /
    defaults: { _controller: ActedLegalDocsBundle:Feedback:addFeedbackRating }
    methods:  POST

feedback_rating:
    path: /rating
    defaults: { _controller: ActedLegalDocsBundle:Feedback:addRating }
    methods:  POST

feedback_artist:
    path: /artist
    defaults: { _controller: ActedLegalDocsBundle:Feedback:getFeedbacks }
    methods:  GET

feedback_average_rating:
    path: /list/{artist}/{page}/{size}
    requirements:
      page: \d+
      size: \d+
    defaults: { _controller: ActedLegalDocsBundle:Feedback:getFeedbacks, page: 1, size: 10 }
    methods:  GET