feedback_feedback_rating:
    path: /
    defaults: { _controller: ActedLegalDocsBundle:Feedback:addFeedbackRating }
    methods:  POST

feedback_rating:
    path: /rating
    defaults: { _controller: ActedLegalDocsBundle:Feedback:addRating }
    methods:  POST

feedback_artist_rating:
    path: /artist/rating/{artist}
    defaults: { _controller: ActedLegalDocsBundle:Feedback:getAverageRating }
    methods:  GET

feedback_artist:
    path: /artist/{artist}/{page}/{size}
    requirements:
      page: \d+
      size: \d+
    defaults: { _controller: ActedLegalDocsBundle:Feedback:getFeedbacks, page: 1, size: 3 }
    methods:  GET