order_get_by_id:
    path:     /{orderId}
    defaults: { _controller: ActedLegalDocsBundle:Order:getOrderById, _format: json }
    methods:  GET

order_accept_field:
    path:     /accept/{orderId}/{fieldId}/{value}
    defaults: { _controller: ActedLegalDocsBundle:Order:acceptOrderField, _format: json }

order_payment:
    path:     /pay/{orderId}
    defaults: { _controller: ActedLegalDocsBundle:Order:pay, _format: html }
    methods: GET

order_payment_success:
    path:    /pay/success/{orderId}
    defaults: { _controller: ActedLegalDocsBundle:Order:paySuccess, _format: html }

order_save_details:
    path:    /save_details/{orderId}
    methods: POST
    defaults: { _controller: ActedLegalDocsBundle:Order:saveDetails, _format: json }

order_update:
    path:     /{orderId}
    defaults: { _controller: ActedLegalDocsBundle:Order:updateOrder, _format: json }
    methods:  PUT

order_cancel:
    path:     /{orderId}/{type}
    defaults: { _controller: ActedLegalDocsBundle:Order:cancelOrder, _format: json, type: null }
    methods:  DELETE
    requirements:
      orderId: \d+

order_set_tech_reqs:
    path:    /save_techreqs/{orderId}
    methods: POST
    defaults: {_controller:ActedLegalDocsBundle:Order:saveTechReqs, _format: json }