performancecontract_index:
    path:     /
    defaults: { _controller: "ActedLegalDocsBundle:PerformanceContract:index" }
    methods:  GET

performancecontract_show:
    path:     /{id}/show
    defaults: { _controller: "ActedLegalDocsBundle:PerformanceContract:show" }
    methods:  GET

performancecontract_new:
    path:     /new
    defaults: { _controller: "ActedLegalDocsBundle:PerformanceContract:new" }
    methods:  [GET, POST]

performancecontract_edit:
    path:     /{id}/edit
    defaults: { _controller: "ActedLegalDocsBundle:PerformanceContract:edit" }
    methods:  [GET, POST]

performancecontract_delete:
    path:     /{id}/delete
    defaults: { _controller: "ActedLegalDocsBundle:PerformanceContract:delete" }
    methods:  DELETE
