price_service_create:
    path: /service/create
    defaults: { _controller: ActedLegalDocsBundle:Service:create }
    methods:  POST

price_performance_create:
    path: /{slug}/performance/create
    defaults: { _controller: ActedLegalDocsBundle:Performance:new }
    methods:  POST
