profile_list:
    path:     /list
    defaults: { _controller: ActedLegalDocsBundle:Profile:list }
    methods:  GET
profile_show:
    path:     /{artist}
    defaults: { _controller: ActedLegalDocsBundle:Profile:show }
    methods:  GET