profile_list:
    path:     /list
    defaults: { _controller: ActedLegalDocsBundle:Profile:list }
    methods:  GET
profile_show:
    path:     /{slug}
    defaults: { _controller: ActedLegalDocsBundle:Profile:show }
    methods:  GET
profile_offers_list:
    path:     /{slug}/offer
    defaults: { _controller: ActedLegalDocsBundle:Profile:offers }
    methods:  GET