profile_list:
    path:     /list
    defaults: { _controller: ActedLegalDocsBundle:Profile:list }
    methods:  GET
profile_show:
    path:     /{slug}
    defaults: { _controller: ActedLegalDocsBundle:Profile:show }
    methods:  GET
profile_edit:
    path:     /{slug}/edit
    defaults: { _controller: ActedLegalDocsBundle:Profile:edit }
    methods:  [GET, POST, PATCH, PUT]
profile_performance_list:
    path:     /{slug}/performance
    defaults: { _controller: ActedLegalDocsBundle:Profile:performances }
    methods:  GET
profile_offer_edit:
    path:     /{slug}/offer/{id}/edit
    defaults: { _controller: ActedLegalDocsBundle:Profile:offerEdit }
    methods:  PATCH
profile_feedbacks_list:
    path:     /{slug}/feedback
    defaults: { _controller: ActedLegalDocsBundle:Profile:feedbacks }
    methods:  GET
profile_add_media:
    path:    /{slug}/media/{id}
    defaults: { _controller: ActedLegalDocsBundle:Profile:addMedia }
    methods:  POST
profile_delete_media:
    path:    /{slug}/media/{id}
    defaults: { _controller: ActedLegalDocsBundle:Profile:deleteMedia }
    methods:  DELETE