profile_list:
    path:     /list
    defaults: { _controller: ActedLegalDocsBundle:Profile:list }
    methods:  GET
profile_show:
    path:     /{slug}
    defaults: { _controller: ActedLegalDocsBundle:Profile:show }
    methods:  GET
profile_edit:
    path:     /{slug}/edit
    defaults: { _controller: ActedLegalDocsBundle:Profile:edit }
    methods:  [GET, POST, PATCH, PUT]
profile_edit_page:
    path:     /edit_profile/{slug}
    defaults: { _controller: ActedLegalDocsBundle:Profile:editProfile }
    methods:  [GET]
profile_performance_list:
    path:     /{slug}/performance
    defaults: { _controller: ActedLegalDocsBundle:Profile:performances }
    methods:  GET
profile_performance_delete:
    path:     /{slug}/performance/{id}
    defaults: { _controller: ActedLegalDocsBundle:Profile:deletePerformance }
    methods:  DELETE
profile_offer_edit:
    path:     /{slug}/offer/{id}/edit
    defaults: { _controller: ActedLegalDocsBundle:Profile:offerEdit }
    methods:  PATCH
profile_feedbacks_list:
    path:     /{slug}/feedback
    defaults: { _controller: ActedLegalDocsBundle:Profile:feedbacks }
    methods:  GET
profile_new_media:
    path:    /{slug}/media/new
    defaults: { _controller: ActedLegalDocsBundle:Profile:newMedia }
    methods:  POST
profile_add_media:
    path:    /{slug}/media/{id}
    defaults: { _controller: ActedLegalDocsBundle:Profile:addMedia }
    methods:  POST
profile_delete_media:
    path:    /{slug}/media/{id}
    defaults: { _controller: ActedLegalDocsBundle:Profile:deleteMedia }
    methods:  DELETE