security_login:
    path:     /login
    defaults: { _controller: "ActedLegalDocsBundle:Security:login" }

security_register:
    path:     /register
    defaults: { _controller: "ActedLegalDocsBundle:Security:register" }
    methods: POST

security_confirm:
    path:     /confirm/{token}
    defaults: { _controller: "ActedLegalDocsBundle:Security:confirm" }

security_login_check:
    path:     /login_check
    defaults: { _controller: "ActedLegalDocsBundle:Security:loginCheck" }

security_logout:
    path:     /logout
    defaults: { _controller: "ActedLegalDocsBundle:Security:logout" }

security_resetting_request:
    path:     /resetting/request
    defaults: { _controller: "ActedLegalDocsBundle:Security:sendResetPassword" }

security_resetting_reset:
    path:     /resetting/reset/{token}
    defaults: { _controller: "ActedLegalDocsBundle:Security:reset" }

security_resend_token:
    path:     /resend_token/reset/{token}
    defaults: { _controller: "ActedLegalDocsBundle:Security:resendConfirmationToken" }

security_check_email:
    path: /is_email_exists/{email}
    defaults: { _controller: ActedLegalDocsBundle:Security:isEmailExists }
    methods: GET

security_password_recovery:
    path: /password-recovery
    defaults: { _controller: ActedLegalDocsBundle:Security:passwordRecovery }
    methods: GET

security_sustem_recovery:
    path: /system-recovery
    defaults: { _controller: ActedLegalDocsBundle:Profile:recoverAllProfiles}