service_create:
    path: /package/create
    defaults: { _controller: ActedLegalDocsBundle:Service:createPackage }
    methods:  POST

service_edit:
    path: /{id}/edit
    defaults: { _controller: ActedLegalDocsBundle:Service:edit }
    methods:  PATCH

service_remove:
    path: /{id}/remove
    defaults: { _controller: ActedLegalDocsBundle:Service:remove }
    methods:  DELETE

service_list:
    path: /list/{id}
    defaults: { _controller: ActedLegalDocsBundle:Service:get }
    methods:  GET

service_profile_list:
    path: /{id}/list
    defaults: { _controller: ActedLegalDocsBundle:Service:getList }
    methods:  GET

