Acted\LegalDocsBundle\Entity\Artist:
    type: entity
    table: Artist
    indexes:
      search_index:
        columns: [name, assistant_name]
        flags: [fulltext]
    repositoryClass: Acted\LegalDocsBundle\Repository\ArtistRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
          type: string(128)
        slug:
          type: string(128)
          unique: true
        assistantName:
          type: string(128)
          nullable: true
        website:
          type: string(256)
          nullable: true
        paymentDetails:
          type: string(512)
          nullable: true
        vatRate:
          type: float
          nullable: true
        comments:
          type: string(512)
          nullable: true
        spotlight:
          type: integer
          nullable: true
        workAbroad:
          type: boolean
          options:
            default: false
        searchImage:
          type: string(256)
          nullable: true
    manyToOne:
        city:
          targetEntity: Acted\LegalDocsBundle\Entity\RefCity
        country:
          targetEntity: Acted\LegalDocsBundle\Entity\RefCountry
    oneToOne:
        user:
          targetEntity: Acted\LegalDocsBundle\Entity\User
          joinColumn:
            referencedColumnName: id
            onDelete: CASCADE
          inversedBy: artist
    oneToMany:
        ratings:
            targetEntity: Acted\LegalDocsBundle\Entity\ArtistRating
            mappedBy: artist
            cascade: ["remove", "persist"]
        recommends:
            targetEntity: Acted\LegalDocsBundle\Entity\Recommend
            mappedBy: artist
            cascade: ["remove", "persist"]
        technicalRequirements:
            targetEntity: Acted\LegalDocsBundle\Entity\TechnicalRequirement
            mappedBy: artist
        feedbacks:
            targetEntity: Acted\LegalDocsBundle\Entity\Feedback
            mappedBy: artist
        eventArtists:
            targetEntity: Acted\LegalDocsBundle\Entity\EventArtist
            mappedBy: artist

    lifecycleCallbacks: {  }
