Acted\LegalDocsBundle\Entity\Artist:
    type: entity
    table: Artist
    repositoryClass: Acted\LegalDocsBundle\Repository\ArtistRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
          type: string(128)
        slug:
          type: string(128)
        assistantName:
          type: string(128)
          nullable: true
        website:
          type: string(256)
          nullable: true
        paymentDetails:
          type: string(512)
          nullable: true
        vatRate:
          type: float
          nullable: true
        comments:
          type: string(512)
          nullable: true
    manyToOne:
        city:
          targetEntity: Acted\LegalDocsBundle\Entity\RefCity
    oneToOne:
        user:
          targetEntity: Acted\LegalDocsBundle\Entity\User

    lifecycleCallbacks: {  }
