Acted\LegalDocsBundle\Entity\Artist:
    type: entity
    table: Artist
    repositoryClass: Acted\LegalDocsBundle\Repository\ArtistRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
          type: integer(20)
          notnull: true
        name:
          type: string(128)
          notnull: true
        assistantName:
          type: string(128)
        website:
          type: string(256)
        paymentDetails:
          type: string(512)
        vatRate:
          type: float
        comments:
          type: string(512)
        cityId:
          type: integer(11)
          notnull: true
    lifecycleCallbacks: {  }
