Acted\LegalDocsBundle\Entity\ArtistRating:
    type: entity
    table: ArtistRating
    repositoryClass: Acted\LegalDocsBundle\Repository\ArtistRatingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventId:
          type: integer(20)
          notnull: true
        artistId:
          type: integer(20)
          notnull: true
        rating:
          type: integer(3)
          notnull: true
        title:
          type: string(128)
        comments:
          type: string(512)
        ratingDateTime:
          type: datetime
          notnull: true
    lifecycleCallbacks: {  }
