Acted\LegalDocsBundle\Entity\ArtistAgenda:
    type: entity
    table: ArtistAgenda
    repositoryClass: Acted\LegalDocsBundle\Repository\ArtistAgendaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        profileId:
          type: integer(20)
          notnull: true
        title:
          type: string(128)
          notnull: true
        description:
          type: string(512)
          notnull: true
        startingDatetime:
          type: datetime
        endingDatetime:
          type: datetime
    lifecycleCallbacks: {  }
