Acted\LegalDocsBundle\Entity\ArtistRating:
    type: entity
    table: ArtistRating
    repositoryClass: Acted\LegalDocsBundle\Repository\ArtistRatingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        rating:
          type: integer(3)
        title:
          type: string(128)
          nullable: true
        comments:
          type: string(512)
          nullable: true
        ratingDateTime:
          type: datetime
    manyToOne:
        event:
          targetEntity: Acted\LegalDocsBundle\Entity\Event
        artist:
          targetEntity: Acted\LegalDocsBundle\Entity\Artist
          joinColumn:
            referencedColumnName: id
            onDelete: CASCADE
          inversedBy: ratings
    lifecycleCallbacks: {  }
