Acted\LegalDocsBundle\Entity\ChatRoom:
    type: entity
    table: ChatRoom
    repositoryClass: Acted\LegalDocsBundle\Repository\ChatRoomRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        message:
            targetEntity: Acted\LegalDocsBundle\Entity\Message
            mappedBy: chatRoom
    manyToOne:
        artist:
            targetEntity: Acted\LegalDocsBundle\Entity\User
            inversedBy: chatRoomsArtist
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
        client:
            targetEntity: Acted\LegalDocsBundle\Entity\User
            inversedBy: chatRoomsClient
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
        event:
            targetEntity: Acted\LegalDocsBundle\Entity\Event
            inversedBy: chatRooms
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
    oneToOne:
        offer:
            targetEntity: Acted\LegalDocsBundle\Entity\Offer
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
