Acted\LegalDocsBundle\Entity\ChatRoom:
    type: entity
    table: ChatRoom
    repositoryClass: Acted\LegalDocsBundle\Repository\ChatRoomRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        message:
            targetEntity: Acted\LegalDocsBundle\Entity\Message
            mappedBy: chatRoom
    manyToOne:
        artist:
            targetEntity: Acted\LegalDocsBundle\Entity\User
            inversedBy: chatRoomsArtist
        client:
            targetEntity: Acted\LegalDocsBundle\Entity\User
            inversedBy: chatRoomsClient
        event:
            targetEntity: Acted\LegalDocsBundle\Entity\Event
            inversedBy: chatRooms
    oneToOne:
        offer:
            targetEntity: Acted\LegalDocsBundle\Entity\Offer
    lifecycleCallbacks: {  }
