Acted\LegalDocsBundle\Entity\Client:
    type: entity
    table: Client
    repositoryClass: Acted\LegalDocsBundle\Repository\ClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        clientType:
          type: string(32)
          nullable: true
        company:
          type: string(128)
        comments:
          type: string(512)
        address:
          type: string(256)
          nullable: true
        cityId:
          type: integer(11)
          nullable: true

    oneToOne:
        user:
          targetEntity: Acted\LegalDocsBundle\Entity\User
          joinColumn:
            name: user_id
            referencedColumnName: id

    lifecycleCallbacks: {  }
