Acted\LegalDocsBundle\Entity\Client:
    type: entity
    table: Client
    repositoryClass: Acted\LegalDocsBundle\Repository\ClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
          type: integer(20)
          notnull: true
        clientType:
          type: string(32)
          notnull: true
        company:
          type: string(128)
        comments:
          type: string(512)
        address:
          type: string(256)
          notnull: true
        cityId:
          type: integer(11)
          notnull: true
    lifecycleCallbacks: {  }
