Acted\LegalDocsBundle\Entity\Document:
    type: entity
    table: Document
    repositoryClass: Acted\LegalDocsBundle\Repository\DocumentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventId:
          type: integer(20)
          notnull: true
        documentType:
          type: string(32)
          notnull: true
        documentName:
          type: string(256)
          notnull: true
          unique: true
        documentSize:
          type: integer(9)
          notnull: true
    lifecycleCallbacks: {  }
