Acted\LegalDocsBundle\Entity\DynMedia:
    type: entity
    table: null
    repositoryClass: Acted\LegalDocsBundle\Repository\DynMediaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mediaId:
          type: bigint(20)
          primary: true
          autoincrement: true
          notnull: true
        mediaType:
          type: varchar(32)
          notnull: true
        name:
          type: varchar(128)
          notnull: true
        link:
          type: varchar(256)
        mediaSize:
          type: mediumint(9)
        position:
          type: int(11)
          notnull: true
        active:
          type: boolean
          notnull: true
    lifecycleCallbacks: {  }
