Acted\LegalDocsBundle\Entity\DynMessageFile:
    type: entity
    table: null
    repositoryClass: Acted\LegalDocsBundle\Repository\DynMessageFileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        messageFileId:
          type: bigint(20)
          primary: true
          autoincrement: true
          notnull: true
        messageId:
          type: bigint(20)
          notnull: true
        fileName:
          type: bigint(20)
          notnull: true
        fileSize:
          type: mediumint(9)
          notnull: true
    lifecycleCallbacks: {  }
