Acted\LegalDocsBundle\Entity\DynOffer:
    type: entity
    table: null
    repositoryClass: Acted\LegalDocsBundle\Repository\DynOfferRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        offerId:
          type: bigint(20)
          primary: true
          autoincrement: true
          notnull: true
        performanceId:
          type: bigint(20)
          notnull: true
        title:
          type: varchar(128)
          notnull: true
          unique: true
        price:
          type: double
          notnull: true
        currencyId:
          type: int(11)
          notnull: true
        depositValue:
          type: double
          notnull: true
        depositType:
          type: varchar(32)
          notnull: true
        paymentTerms:
          type: varchar(256)
        comments:
          type: varchar(256)
    lifecycleCallbacks: {  }
