Acted\LegalDocsBundle\Entity\DynPerformanceMedia:
    type: entity
    table: null
    repositoryClass: Acted\LegalDocsBundle\Repository\DynPerformanceMediaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mediaId:
          type: bigint(20)
          primary: true
          notnull: true
        performanceId:
          type: bigint(20)
          primary: true
          notnull: true
    lifecycleCallbacks: {  }
