Acted\LegalDocsBundle\Entity\EventExtra:
    type: entity
    table: EventExtra
    repositoryClass: Acted\LegalDocsBundle\Repository\EventExtraRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventId:
          type: integer(20)
          notnull: true
        name:
          type: string(128)
          notnull: true
        price:
          type: double
          notnull: true
        currencyId:
          type: integer(11)
          notnull: true
        comments:
          type: string(256)
    lifecycleCallbacks: {  }
