Acted\LegalDocsBundle\Entity\Event:
    type: entity
    table: Event
    repositoryClass: Acted\LegalDocsBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventRef:
          type: string(64)
          notnull: true
          unique: true
        userId:
          type: integer(20)
          notnull: true
        title:
          type: string(128)
          notnull: true
        description:
          type: string(512)
        eventTypeId:
          type: integer(11)
          notnull: true
        isInternational:
          type: boolean
          notnull: true
        address:
          type: string(256)
          notnull: true
        cityId:
          type: integer(11)
          notnull: true
        budget:
          type: double
        currencyId:
          type: integer(11)
        startingDate:
          type: datetime
        endingDate:
          type: datetime
        timing:
          type: string(128)
        comments:
          type: string(512)
    lifecycleCallbacks: {  }
