Acted\LegalDocsBundle\Entity\Event:
    type: entity
    table: Event
    repositoryClass: Acted\LegalDocsBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventRef:
          type: string(64)
          unique: true
        title:
          type: string(128)
        description:
          type: string(512)
          nullable: true
        isInternational:
          type: boolean
        address:
          type: string(256)
        budget:
          type: float
          nullable: true
        currencyId:
          type: integer(11)
          nullable: true
        startingDate:
          type: datetime
          nullable: true
        endingDate:
          type: datetime
          nullable: true
        timing:
          type: string(128)
          nullable: true
        comments:
          type: string(512)
          nullable: true
    manyToOne:
          user:
            targetEntity: Acted\LegalDocsBundle\Entity\User
          city:
            targetEntity: Acted\LegalDocsBundle\Entity\RefCity
          eventType:
            targetEntity: Acted\LegalDocsBundle\Entity\RefEventType
          venueType:
            targetEntity: Acted\LegalDocsBundle\Entity\RefVenueType
    oneToMany:
        chatRooms:
          targetEntity: Acted\LegalDocsBundle\Entity\ChatRoom
          mappedBy: event

    lifecycleCallbacks: {  }
