Acted\LegalDocsBundle\Entity\EventOffer:
    type: entity
    table: EventOffer
    repositoryClass: Acted\LegalDocsBundle\Repository\EventOfferRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
          type: string(32)
          notnull: true
        price:
          type: float
          nullable: true
        currencyId:
          type: integer(11)
          nullable: true
        depositValue:
          type: float
          nullable: true
        depositType:
          type: string(32)
          nullable: true
        paymentTerms:
          type: string(256)
          nullable: true
        comments:
          type: string(256)
          nullable: true
        sendDateTime:
          type: datetime
          notnull: true
        readDateTime:
          type: datetime
          nullable: true
    manyToOne:
        event:
          targetEntity: Acted\LegalDocsBundle\Entity\Event
        offer:
          targetEntity: Acted\LegalDocsBundle\Entity\Offer
    lifecycleCallbacks: {  }
