Acted\LegalDocsBundle\Entity\Media:
    type: entity
    table: Media
    repositoryClass: Acted\LegalDocsBundle\Repository\MediaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mediaType:
          type: string(32)
          notnull: true
        name:
          type: string(128)
          notnull: true
        link:
          type: string(256)
        mediaSize:
          type: integer(9)
        position:
          type: integer(11)
          notnull: true
        active:
          type: boolean
          notnull: true
    lifecycleCallbacks: {  }
