Acted\LegalDocsBundle\Entity\Media:
    type: entity
    table: Media
    repositoryClass: Acted\LegalDocsBundle\Repository\MediaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mediaType:
          type: string(32)
          notnull: true
        name:
          type: string(255)
          notnull: true
        link:
          type: string(256)
        mediaSize:
          type: integer(9)
          nullable: true
        position:
          type: integer(11)
          notnull: true
          options:
            default: 0
        active:
          type: boolean
          notnull: true
          options:
            default: true
        thumbnail:
          type: string(256)
          nullable: true
    manyToMany:
        performances:
          targetEntity: Acted\LegalDocsBundle\Entity\Performance
          mappedBy: media
        profiles:
          targetEntity: Acted\LegalDocsBundle\Entity\Profile
          mappedBy: media
    oneToMany:
        homespotlights:
          targetEntity: Acted\LegalDocsBundle\Entity\Homespotlight
          cascade: ["remove"]
          mappedBy: media
    lifecycleCallbacks: {  }
