Acted\LegalDocsBundle\Entity\MessageFile:
    type: entity
    table: MessageFile
    repositoryClass: Acted\LegalDocsBundle\Repository\MessageFileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fileName:
          type: string(256)
          notnull: true
        fileSize:
          type: integer(9)
          nullable: true
    oneToOne:
        media:
            targetEntity: Acted\LegalDocsBundle\Entity\Media
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
    manyToOne:
        message:
            targetEntity: Acted\LegalDocsBundle\Entity\Message
            inversedBy: files
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
