Acted\LegalDocsBundle\Entity\Message:
    type: entity
    table: Message
    repositoryClass: Acted\LegalDocsBundle\Repository\MessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        subject:
          type: string(128)
          notnull: true
        messageText:
          type: text
          nullable: true
        sendDateTime:
          type: datetime
          notnull: true
        readDateTime:
          type: datetime
          nullable: true
        archived:
          type: boolean
          options:
            default: false
    manyToOne:
        chatRoom:
            targetEntity: Acted\LegalDocsBundle\Entity\ChatRoom
            inversedBy: message
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
        receiverUser:
            targetEntity: Acted\LegalDocsBundle\Entity\User
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
        senderUser:
            targetEntity: Acted\LegalDocsBundle\Entity\User
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
    oneToMany:
        files:
          targetEntity: Acted\LegalDocsBundle\Entity\MessageFile
          mappedBy: message
          cascade: ["remove", "persist"]
    lifecycleCallbacks: {  }
