Acted\LegalDocsBundle\Entity\Message:
    type: entity
    table: Message
    repositoryClass: Acted\LegalDocsBundle\Repository\MessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        senderUserId:
          type: integer(20)
          notnull: true
        receiverUserId:
          type: integer(20)
          notnull: true
        subject:
          type: string(128)
          notnull: true
        messageText:
          type: string(512)
          notnull: true
        sendDateTime:
          type: datetime
          notnull: true
        readDateTime:
          type: datetime
          nullable: true
    manyToOne:
        chatRoom:
            targetEntity: Acted\LegalDocsBundle\Entity\ChatRoom
            inversedBy: message
    lifecycleCallbacks: {  }
