Acted\LegalDocsBundle\Entity\Offer:
    type: entity
    table: Offer
    repositoryClass: Acted\LegalDocsBundle\Repository\OfferRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
          type: string(128)
          unique: true
        price:
          type: float
        currencyId:
          type: integer(11)
        depositValue:
          type: float
          notnull: true
          type: string(32)
        paymentTerms:
          type: string(256)
          nullable: true
        comments:
          type: string(256)
          nullable: true
    manyToOne:
        performance:
          targetEntity: Acted\LegalDocsBundle\Entity\Performance
    lifecycleCallbacks: {  }
