Acted\LegalDocsBundle\Entity\Offer:
    type: entity
    table: Offer
    repositoryClass: Acted\LegalDocsBundle\Repository\OfferRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        performanceId:
          type: integer(20)
          notnull: true
        title:
          type: string(128)
          notnull: true
          unique: true
        price:
          type: float
          notnull: true
        currencyId:
          type: integer(11)
          notnull: true
        depositValue:
          type: float
          notnull: true
        depositType:
          type: string(32)
          notnull: true
        paymentTerms:
          type: string(256)
        comments:
          type: string(256)
    lifecycleCallbacks: {  }
