Acted\LegalDocsBundle\Entity\Offer:
    type: entity
    table: Offer
    repositoryClass: Acted\LegalDocsBundle\Repository\OfferRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
          type: string(128)
          unique: true
        price:
          type: float
          nullable: true
        currencyId:
          type: integer(11)
          nullable: true
        depositValue:
          type: float
          nullable: true
          type: string(32)
        paymentTerms:
          type: string(256)
          nullable: true
        comments:
          type: text
          nullable: true
    manyToMany:
        performances:
          targetEntity: Acted\LegalDocsBundle\Entity\Performance
          inversedBy: offers
    oneToMany:
        eventOffer:
          targetEntity: Acted\LegalDocsBundle\Entity\EventOffer
          mappedBy: offer
    lifecycleCallbacks: {  }
