Acted\LegalDocsBundle\Entity\OrderItemService:
  type: entity
  manyToOne:
    service:
      targetEntity: Acted\LegalDocsBundle\Entity\Service
      joinColumn:
          name: service_id
          referencedColumnName: id