Acted\LegalDocsBundle\Entity\Performance:
    type: entity
    table: Performance
    indexes:
        search_index:
            columns: [title, tech_requirement]
            flags: [fulltext]
    repositoryClass: Acted\LegalDocsBundle\Repository\PerformanceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
          type: string(128)
        techRequirement:
          type: string(512)
          nullable: true
        status:
          type: string(128)
          options:
            default: 'draft'
        isVisible:
          type: boolean
          options:
            default: true
        deletedTime:
          type: datetime
          nullable: true
    manyToOne:
        profile:
          targetEntity: Acted\LegalDocsBundle\Entity\Profile
          inversedBy: performances
          joinColumn:
              referencedColumnName: id
              onDelete: CASCADE
    manyToMany:
        media:
          targetEntity: Acted\LegalDocsBundle\Entity\Media
          inversedBy: performances
        offers:
          targetEntity: Acted\LegalDocsBundle\Entity\Offer
          mappedBy: performances
    oneToMany:
        packages:
          targetEntity: Acted\LegalDocsBundle\Entity\Package
          mappedBy: performance
    lifecycleCallbacks: {  }
