Acted\LegalDocsBundle\Entity\PerformanceMedia:
    type: entity
    table: PerformanceMedia
    repositoryClass: Acted\LegalDocsBundle\Repository\PerformanceMediaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mediaId:
          type: integer(20)
          notnull: true
        performanceId:
          type: integer(20)
          notnull: true
    lifecycleCallbacks: {  }
