Acted\LegalDocsBundle\Entity\Performance:
    type: entity
    table: Performance
    repositoryClass: Acted\LegalDocsBundle\Repository\PerformanceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
          type: string(128)
        techRequirement:
          type: string(512)
          nullable: true
    manyToOne:
        profile:
          targetEntity: Acted\LegalDocsBundle\Entity\Profile
    oneToMany:
        offers:
          targetEntity: Acted\LegalDocsBundle\Entity\Offer
          mappedBy: performance
    manyToMany:
        media:
          targetEntity: Acted\LegalDocsBundle\Entity\Media
    lifecycleCallbacks: {  }
