Acted\LegalDocsBundle\Entity\Price:
    type: entity
    table: Price
    repositoryClass: Acted\LegalDocsBundle\Repository\PriceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
      amount:
        type: decimal(12,2)
        #type: integer(11)
    oneToOne:
      rate:
        targetEntity: Acted\LegalDocsBundle\Entity\Rate
        mappedBy: price

    lifecycleCallbacks: {  }
