Acted\LegalDocsBundle\Entity\Price:
    type: entity
    table: Price
    repositoryClass: Acted\LegalDocsBundle\Repository\PriceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
      deletedTime:
        type: datetime
        nullable: true
    manyToOne:
      performances:
        targetEntity: Acted\LegalDocsBundle\Entity\Performance
        inversedBy: price
        joinColumn:
          onDelete: RESTRICT
      profile:
        targetEntity: Acted\LegalDocsBundle\Entity\Profile
        inversedBy: prices
        joinColumn:
          onDelete: "SET NULL"
    oneToMany:
      services:
        targetEntity: Acted\LegalDocsBundle\Entity\Service
        mappedBy: price
        joinColumn:
          onDelete: RESTRICT
      pricePackages:
        targetEntity: Acted\LegalDocsBundle\Entity\PricePackage
        mappedBy: price
        joinColumn:
          onDelete: RESTRICT
    lifecycleCallbacks: {  }
