Acted\LegalDocsBundle\Entity\Profile:
    type: entity
    table: Profile
    repositoryClass: Acted\LegalDocsBundle\Repository\ProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
          type: integer(20)
          notnull: true
        title:
          type: string(128)
          notnull: true
        header:
          type: string(512)
        description:
          type: text
        isInternational:
          type: boolean
          notnull: true
        performanceRange:
          type: integer(8)
        paymentTypeId:
          type: integer(11)
          notnull: true
        active:
          type: boolean
          notnull: true
    oneToOne:
        user:
          targetEntity: Acted\LegalDocsBundle\Entity\User
          inversedBy: profile
    manyToMany:
        media:
          targetEntity: Acted\LegalDocsBundle\Entity\Media
          inversedBy: profiles
        categories:
          targetEntity: Acted\LegalDocsBundle\Entity\Category
    oneToMany:
        performances:
          targetEntity: Acted\LegalDocsBundle\Entity\Performance
          mappedBy: profile


    lifecycleCallbacks: {  }
