Acted\LegalDocsBundle\Entity\Profile:
    type: entity
    table: Profile
    repositoryClass: Acted\LegalDocsBundle\Repository\ProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
          type: string(128)
        header:
          type: string(512)
          nullable: true
        description:
          type: text
          nullable: true
        isInternational:
          type: boolean
          options:
            default: false
        performanceRange:
          type: integer(8)
          nullable: true
        paymentTypeId:
          type: integer(11)
        active:
          type: boolean
          options:
            default: false
    oneToOne:
        user:
          targetEntity: Acted\LegalDocsBundle\Entity\User
          inversedBy: profile
    manyToMany:
        media:
          targetEntity: Acted\LegalDocsBundle\Entity\Media
          inversedBy: profiles
        categories:
          targetEntity: Acted\LegalDocsBundle\Entity\Category
    oneToMany:
        performances:
          targetEntity: Acted\LegalDocsBundle\Entity\Performance
          mappedBy: profile


    lifecycleCallbacks: {  }
