Acted\LegalDocsBundle\Entity\ProfileMedia:
    type: entity
    table: ProfileMedia
    repositoryClass: Acted\LegalDocsBundle\Repository\ProfileMediaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mediaId:
          type: integer(20)
          notnull: true
        profileId:
          type: integer(20)
          notnull: true
    lifecycleCallbacks: {  }
