Acted\LegalDocsBundle\Entity\Profile:
    type: entity
    table: Profile
    indexes:
        search_index:
            columns: [title, description, header]
            flags: [fulltext]
    repositoryClass: Acted\LegalDocsBundle\Repository\ProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
          type: string(128)
        header:
          type: string(512)
          nullable: true
        description:
          type: text
          nullable: true
        isInternational:
          type: boolean
          options:
            default: false
        performanceRange:
          type: integer(8)
          nullable: true
        paymentTypeId:
          type: integer(11)
        active:
          type: boolean
          options:
            default: false
    oneToOne:
        user:
          targetEntity: Acted\LegalDocsBundle\Entity\User
          inversedBy: profile
    manyToMany:
        media:
          targetEntity: Acted\LegalDocsBundle\Entity\Media
          inversedBy: profiles
        categories:
          targetEntity: Acted\LegalDocsBundle\Entity\Category
    oneToMany:
        packages:
          targetEntity: Acted\LegalDocsBundle\Entity\Package
          mappedBy: profile
        performances:
          targetEntity: Acted\LegalDocsBundle\Entity\Performance
          mappedBy: profile
          orderBy: { 'id': 'DESC' }
        services:
          targetEntity: Acted\LegalDocsBundle\Entity\Service
          mappedBy: profile
          orderBy: { 'id': 'DESC' }
    lifecycleCallbacks: {  }
