Acted\LegalDocsBundle\Entity\RefCurrency:
    type: entity
    table: RefCurrency
    repositoryClass: Acted\LegalDocsBundle\Repository\RefCurrencyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        isoCode:
          type: string(3)
          notnull: true
          unique: true
        symbol:
          type: string(8)
          notnull: true
    lifecycleCallbacks: {  }
