Acted\LegalDocsBundle\Entity\RefCity:
    type: entity
    table: RefCity
    repositoryClass: Acted\LegalDocsBundle\Repository\RefCityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
          type: string(128)
          notnull: true
          unique: true
        latitude:
          type: decimal
          scale: 12
          precision: 18
          nullable: true
        longitude:
          type: decimal
          scale: 12
          precision: 18
          nullable: true
        placeId:
          type: text
          nullable: true
    manyToOne:
        region:
          targetEntity: Acted\LegalDocsBundle\Entity\RefRegion
          inversedBy: cities
    lifecycleCallbacks: {  }
