Acted\LegalDocsBundle\Entity\RefCountry:
    type: entity
    table: RefCountry
    repositoryClass: Acted\LegalDocsBundle\Repository\RefCountryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
          type: string(128)
          notnull: true
          unique: true
    oneToMany:
        regions:
          targetEntity: Acted\LegalDocsBundle\Entity\RefRegion
          mappedBy: country
    manyToOne:
        refCurrency:
          targetEntity: Acted\LegalDocsBundle\Entity\RefCurrency
          inversedBy: refCountry
          joinColumn:
            onDelete: "SET NULL"
    lifecycleCallbacks: {  }
