Acted\LegalDocsBundle\Entity\RefCurrency:
    type: entity
    table: null
    repositoryClass: Acted\LegalDocsBundle\Repository\RefCurrencyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        currencyId:
          type: int(11)
          primary: true
          autoincrement: true
          notnull: true
        isoCode:
          type: varchar(3)
          notnull: true
          unique: true
        symbol:
          type: varchar(8)
          notnull: true
    lifecycleCallbacks: {  }
