Acted\LegalDocsBundle\Entity\RefCity:
    type: entity
    table: RefCity
    repositoryClass: Acted\LegalDocsBundle\Repository\RefCityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
          type: string(128)
          notnull: true
          unique: true
        countryId:
          type: integer(11)
          notnull: true
        latitude:
          type: decimal
          scale: 8
          nullable: true
        longitude:
          type: decimal
          scale: 8
          nullable: true
    lifecycleCallbacks: {  }
