Acted\LegalDocsBundle\Entity\RefEventType:
    type: entity
    table: RefEventType
    repositoryClass: Acted\LegalDocsBundle\Repository\RefEventTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventType:
          type: string(32)
          notnull: true
          unique: true
    lifecycleCallbacks: {  }
