Acted\LegalDocsBundle\Entity\RefPaymentType:
    type: entity
    table: RefPaymentType
    repositoryClass: Acted\LegalDocsBundle\Repository\RefPaymentTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        paymentType:
          type: string(32)
          notnull: true
          unique: true
    lifecycleCallbacks: {  }
