Acted\LegalDocsBundle\Entity\RefRight:
    type: entity
    table: RefRight
    repositoryClass: Acted\LegalDocsBundle\Repository\RefRightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
          type: string(32)
          notnull: true
          unique: true
        name:
          type: string(64)
          notnull: true
    lifecycleCallbacks: {  }
