Acted\LegalDocsBundle\Entity\RefRole:
    type: entity
    table: RefRole
    repositoryClass: Acted\LegalDocsBundle\Repository\RefRoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
          type: string(32)
          notnull: true
          unique: true
        name:
          type: string(64)
          notnull: true
    manyToMany:
        users:
          targetEntity: Acted\LegalDocsBundle\Entity\User
          mappedBy: roles
    lifecycleCallbacks: {  }
