Acted\LegalDocsBundle\Entity\RefRoleRight:
    type: entity
    table: RefRoleRight
    repositoryClass: Acted\LegalDocsBundle\Repository\RefRoleRightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        roleId:
          type: integer(11)
          notnull: true
        rightId:
          type: integer(11)
          notnull: true
    lifecycleCallbacks: {  }
