Acted\LegalDocsBundle\Entity\RefRole:
    type: entity
    table: null
    repositoryClass: Acted\LegalDocsBundle\Repository\RefRoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        roleId:
          type: int(11)
          primary: true
          autoincrement: true
          notnull: true
        code:
          type: varchar(32)
          notnull: true
          unique: true
        name:
          type: varchar(64)
          notnull: true
    lifecycleCallbacks: {  }
