Acted\LegalDocsBundle\Entity\RefTranslation:
    type: entity
    table: RefTranslation
    repositoryClass: Acted\LegalDocsBundle\Repository\RefTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        en:
          type: string(512)
          notnull: true
        fr:
          type: string(512)
          notnull: true
    lifecycleCallbacks: {  }
