Acted\LegalDocsBundle\Entity\Service:
    type: entity
    table: Service
    repositoryClass: Acted\LegalDocsBundle\Repository\ServiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
          type: string(128)
        isVisible:
          type: boolean
          options:
            default: true
        isQuotation:
          type: boolean
          options:
            default: false
        deletedTime:
          type: datetime
          nullable: true
    oneToMany:
      packages:
        targetEntity: Acted\LegalDocsBundle\Entity\Package
        mappedBy: service
      serviceRequestQuotations:
        targetEntity: Acted\LegalDocsBundle\Entity\ServiceRequestQuotation
        mappedBy: service
    manyToOne:
      profile:
        targetEntity: Acted\LegalDocsBundle\Entity\Profile
        inversedBy: services
    lifecycleCallbacks: {  }
