Acted\LegalDocsBundle\Entity\Staff:
    type: entity
    table: Staff
    repositoryClass: Acted\LegalDocsBundle\Repository\StaffRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
          type: integer(20)
          notnull: true
        roleId:
          type: integer(11)
          notnull: true
        signature:
          type: string(512)
    lifecycleCallbacks: {  }
