Acted\LegalDocsBundle\Entity\Template:
    type: entity
    table: Template
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type_id:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: type_id
        template:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        is_active:
            type: boolean
            nullable: false
            column: is_active
    lifecycleCallbacks: {  }
