Acted\LegalDocsBundle\Entity\User:
    type: entity
    table: User
    repositoryClass: Acted\LegalDocsBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
          type: string(128)
          notnull: true
        lastname:
          type: string(128)
          notnull: true
        email:
          type: string(256)
          notnull: true
          unique: true
        passwordHash:
          type: string(256)
          notnull: true
        primaryPhone:
          type: string(32)
          notnull: true
          unique: true
        secondaryPhone:
          type: string(32)
        active:
          type: boolean
          notnull: true
    lifecycleCallbacks: {  }
