Acted\LegalDocsBundle\Entity\User:
    type: entity
    table: User
    repositoryClass: Acted\LegalDocsBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
          type: string(128)
        lastname:
          type: string(128)
        email:
          type: string(100)
          notnull: true
          unique: true
        passwordHash:
          type: string(256)
          notnull: true
        primaryPhone:
          type: string(32)
          unique: true
          nullable: true
        secondaryPhone:
          type: string(32)
          nullable: true
        active:
          type: boolean
          options:
            default: false
        fake:
          type: boolean
          options:
            default: false
        avatar:
          type: string(256)
          nullable: true
        background:
          type: string(256)
          nullable: true
        confirmationToken:
          type: string(255)
          nullable: true
        passwordRequestedAt:
          type: datetime
          nullable: true
    oneToOne:
        profile:
          targetEntity: Acted\LegalDocsBundle\Entity\Profile
          mappedBy: user
        artist:
          targetEntity: Acted\LegalDocsBundle\Entity\Artist
          mappedBy: user
    manyToMany:
        roles:
          targetEntity: Acted\LegalDocsBundle\Entity\RefRole
          inversedBy: users
    oneToMany:
        chatRoomsArtist:
            targetEntity: Acted\LegalDocsBundle\Entity\ChatRoom
            mappedBy: artist
        chatRoomsClient:
            targetEntity: Acted\LegalDocsBundle\Entity\ChatRoom
            mappedBy: client
    lifecycleCallbacks: {  }
