imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: websocket.yml }
    - { resource: "@ActedLegalDocsBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: false }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        gc_probability: 0
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        gc_probability: 0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      performancecontract_dir: "%performancecontract_dir%"
      quotation_dir: "%quotation_dir%"
      invoice_dir: "%invoice_dir%"
      googlemaps:
        key: AIzaSyDLK8SupBcU-H0H0SF0PIar5UP-y-DCrTI

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                MATCH: Acted\LegalDocsBundle\DQL\MatchAgainstFunction
                RADIANS: DoctrineExtensions\Query\Mysql\Radians
            numeric_functions:
                ACOS: DoctrineExtensions\Query\Mysql\Acos
                COS: DoctrineExtensions\Query\Mysql\Cos
                SIN: DoctrineExtensions\Query\Mysql\Sin
        mappings:
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    theme:
        # Simple theme: same as default theme
        simple: ~
        # Advanced theme with almost all enabled plugins
        advanced:
             height: 500
             plugins:
                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
                 - "insertdatetime media nonbreaking save table contextmenu directionality"
                 - "emoticons template paste textcolor"
             toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
             image_advtab: true
             templates:
                 - {title: 'Test template 1', content: 'Test 1'}
                 - {title: 'Test template 2', content: 'Test 2'}
        # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
        bbcode:
             plugins: ["bbcode, code, link, preview"]
             menubar: false
             toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"

knp_paginator:
    page_range: 3
    template:
        pagination: ActedLegalDocsBundle:Default:pagination.html.twig

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            ActedLegalDocsBundle:
                namespace_prefix: ""
                path: "@ActedLegalDocsBundle/Resources/config/serializer"
    handlers:
        datetime:
            default_format: "d/m/Y"
            default_timezone: "UTC"

liip_imagine:
    driver: imagick
    filter_sets:
        thumbnail_filter:
            format: jpeg
            filters:
                strip: ~
                downscale: { max: [300, 200] }
        search_image_thumbnail:
            quality: 100
            filters:
                relative_resize: { widen: 320, mode: outbound }
        avatar_thumbnail:
            quality: 100
            filters:
                relative_resize: { widen: 320, mode: outbound }
        small:
            quality: 100
            filters:
                relative_resize: { widen: 270, mode: outbound }
        medium:
            quality: 100
            filters:
                relative_resize: { widen: 481, mode: outbound }
        big:
            quality: 100
            filters:
                relative_resize: { widen: 1080, mode: outbound }
        background:
            quality: 100
            filters:
                relative_resize: { widen: 3200, mode: outbound }

nelmio_api_doc: ~

fos_rest:
    view:
        serialize_null: true
        view_response_listener: true
        formats:
            json: true
        templating_formats:
            html: false
    serializer:
        serialize_null: true

tweede_golf_swiftmailer_logger:
    loggers:
        entity_logger:
            enabled: true

sentry:
    dsn: "%sentry_dsn%"