# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Acted\LegalDocsBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database_users:
            entity: { class: Acted\LegalDocsBundle\Entity\User, property: email }

    access_control:
        - { path: ^/dashboard/.*, roles: [ROLE_ARTIST, ROLE_CLIENT] }
        - { path: ^/administration/.*, roles: [ROLE_ADMIN] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout: true
            form_login:
                login_path: /?login_form
        administration:
            form_login:
                default_target_path: /administration

            knpu_guard:
                authenticators:
                  - app.form_login_authenticator