# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
    app.twig_extension:
        class: Acted\LegalDocsBundle\Twig\Extension\AppExtension
        public: false
        tags:
            - {name: twig.extension}
        calls:
            - [ setEntityManager, [ "@doctrine.orm.entity_manager" ] ]
    app.form_login_authenticator:
        class: Acted\LegalDocsBundle\Security\FormLoginAuthenticator
        arguments: ["@service_container"]

    app.user.manager:
        class: Acted\LegalDocsBundle\Model\UserManager
        arguments:
          - "@security.encoder_factory"
          - "@doctrine.orm.entity_manager"
          - "@mailer"
          - "@templating.engine.twig"
          - "@router"
          - "%mailer_from_address%"
          - "@liip_imagine.controller"
          - "%avatar_dir%"
          - "%search_image_dir%"
          - %kernel.root_dir%


    app.event.manager:
        class: Acted\LegalDocsBundle\Model\EventsManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mailer"
            - "%mailer_from_address%"
            - "@templating.engine.twig"
            - "@app.user.manager"

    app.chat.manager:
        class: Acted\LegalDocsBundle\Model\ChatManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.root_dir%"

    app.media.manager:
        class: Acted\LegalDocsBundle\Model\MediaManager
        arguments:
            - "%image_upload_dir%"
            - "@liip_imagine.controller"
            - "%file_formats%"
            - "%max_file_size%"
            - "%chat_upload_dir%"

    app.request_quotation.manager:
        class: Acted\LegalDocsBundle\Model\RequestQuotationManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mailer"
            - "%mailer_from_address%"
            - "@templating.engine.twig"
            - "@app.user.manager"

    app.form_errors_serializer:
        class: Acted\LegalDocsBundle\FormErrors\FormErrorsSerializer

    app.artist_voter:
        class: Acted\LegalDocsBundle\Security\ArtistVoter
        tags:
          - {name: security.voter}
        public: false

    app.remove_files.listener:
        class: Acted\LegalDocsBundle\EventListener\RemoveFiles
        arguments: ["%image_upload_dir%"]
        tags:
        - { name: doctrine.event_listener, event: postRemove }

    app.listener.geo:
        class: Acted\LegalDocsBundle\EventListener\GeoListener
        tags:
          - {name: doctrine.event_listener, event: prePersist}

    app.search:
        class: Acted\LegalDocsBundle\Service\DoctrineSearch
        arguments: ["@doctrine.orm.entity_manager", "@knp_paginator", "%fake_users%"]

    app.artist_serializer_subscriber:
        class: Acted\LegalDocsBundle\Serializer\ArtistSerializerSubscriber
        arguments:
          - "@doctrine.orm.default_entity_manager"
        tags:
          - { name: jms_serializer.event_subscriber }

    app.form.type.boolean:
        class: Acted\LegalDocsBundle\Form\Type\BooleanType
        tags:
            - { name: form.type, alias: boolean }