# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
    app.twig_extension:
        class: Acted\LegalDocsBundle\Twig\Extension\AppExtension
        public: false
        tags:
            - {name: twig.extension}
        calls:
            - [ setEntityManager, [ "@doctrine.orm.entity_manager" ] ]
    app.form_login_authenticator:
        class: Acted\LegalDocsBundle\Security\FormLoginAuthenticator
        arguments: ["@service_container"]

    app.user.manager:
        class: Acted\LegalDocsBundle\Model\UserManager
        arguments:
          - "@security.encoder_factory"
          - "@doctrine.orm.entity_manager"
          - "@mailer"
          - "@templating.engine.twig"
          - "@router"
          - "%mailer_from_address%"