gos_web_socket:
    topics:
        - @socket_chat.rpc_topic
    server:
        port: "%web_socket_server_port%"
        host: "%web_socket_server_host%"
        router:
            resources:
                - @ActedLegalDocsBundle/Resources/config/routing/pubsub/routing.yml
    pushers:
        zmq:
            default: true
            host: "%web_socket_pusher_host%"
            port: "%web_socket_pusher_port%"
            persistent: true
            protocol: tcp