api_event:
  path: /events/{event}
  defaults: { _controller: ActedLegalDocsBundle:Events:getEventDataById }
  methods: [GET]
  requirements:
    event: \d+

api_event_edit:
  path: /events/{event}/edit
  defaults: { _controller: ActedLegalDocsBundle:Events:updateEvent }
  methods: [PATCH]

api_venue:
  path: /venues
  methods: [GET]
  defaults: { _controller: ActedLegalDocsBundle:Events:showVenues }