acted_legal_docs_template:
    resource: "@ActedLegalDocsBundle/Resources/config/routing/template.yml"
    prefix:   /template

acted_legal_docs_performancecontract:
    resource: "@ActedLegalDocsBundle/Resources/config/routing/performancecontract.yml"
    prefix:   /performancecontract

acted_legal_docs_invoicetype:
    resource: "@ActedLegalDocsBundle/Resources/config/routing/invoicetype.yml"
    prefix:   /invoicetype

acted_legal_docs_quotationtype:
    resource: "@ActedLegalDocsBundle/Resources/config/routing/quotationtype.yml"
    prefix:   /quotationtype

acted_legal_docs_homepage:
    path:     /
    defaults: { _controller: ActedLegalDocsBundle:Default:index }

acted_legal_docs_profile:
  resource: "@ActedLegalDocsBundle/Resources/config/routing/profile.yml"
  prefix: /profile

acted_legal_docs_performance:
  resource: "@ActedLegalDocsBundle/Resources/config/routing/performance.yml"
  prefix: /profile

acted_legal_docs_user:
  resource: "@ActedLegalDocsBundle/Resources/config/routing/user.yml"
  prefix: /user

acted_legal_docs_security:
  resource: "@ActedLegalDocsBundle/Resources/config/routing/security.yml"

acted_legal_docs_media:
  resource: "@ActedLegalDocsBundle/Resources/config/routing/media.yml"
  prefix: /media

acted_legal_docs_geo:
  resource: "@ActedLegalDocsBundle/Resources/config/routing/geo.yml"
  prefix: /geo

acted_legal_docs_artist:
  resource: "@ActedLegalDocsBundle/Resources/config/routing/artist.yml"
  prefix: /

acted_legal_docs_search:
  path: /search/{category}
  defaults: { _controller: ActedLegalDocsBundle:Search:index, category: "" }
  methods:  [GET]