Acted\LegalDocsBundle\Entity\EventOffer:
    exclusion_policy: NONE
    properties:
        status:
            groups: [Default, getEvent, all_messages, chat_list]
        event:
            groups: [Default, getEvent]
        offer:
            groups: [getEvent]
    virtual_properties:
        getTimeFromAdd:
            serialized_name: time_from_add
            groups: [chat_list, message, chat_room, all_messages, getEvent]