Acted\LegalDocsBundle\Entity\Order:
  properties:
    id:
      groups: [order]

    items:
      groups: [order]

    artist:
      groups: [order]

    event:
      groups: [order]

    client:
      groups: [order]

    performances:
      groups: [order]

    services:
      groups: [order]

    guaranteedBalanceTerm:
      groups: [order]

    guaranteedDepositTerm:
      groups: [order]

    status:
      groups: [order]

    chat:
      groups: [order]

    performance_start_time:
      groups: [order]

    deposit_amount:
      groups: [order]

    deposit_ballance:
      groups: [order]