Acted\LegalDocsBundle\Entity\RequestQuotation:
    exclusion_policy: NONE
    properties:
        status:
            groups: []
    virtual_properties:
        getEvent:
            serialized_name: event
            groups: []