Acted\LegalDocsBundle\Entity\Service:
#  exclusion_policy: NONE
  properties:
    id:
      groups: [price_service, order]
    title:
      groups: [price_service, order]
    packages:
      groups: []
  virtual_properties:
    getPackages:
      serialized_name: packages
      groups: [price_service]
    getExistedPackages:
      serialized_name: packages
      groups: [order]