Acted\LegalDocsBundle\Entity\Performance:
    exclusion_policy: NONE
    properties:
        id:
            groups: [chat_list, chat_room, all_messages, performance_create]
        title:
            groups: [chat_list, chat_room, all_messages]
        status:
            groups: [performance_create]
        profile:
            groups: [getEvent]