Acted\LegalDocsBundle\Entity\Message:
    exclusion_policy: NONE
    properties:
        id:
            groups: [chat_list, chat_room, message]
        messageText:
            groups: [chat_list, chat_room, message]
        sendDateTime:
            groups: [chat_list, chat_room, message]
        readDateTime:
            groups: [chat_list, chat_room, message]
        receiverUser:
            groups: [chat_list, message]
        senderUser:
            groups: [chat_room, message]
