Acted\LegalDocsBundle\Entity\EventOffer:
    exclusion_policy: NONE
    properties:
        status:
            groups: [Default, getEvent, all_messages]
        event:
            groups: [Default, getEvent]