Acted\LegalDocsBundle\Entity\DocumentTechnicalRequirement:
    exclusion_policy: NONE
    properties:
        name:
            groups: []
        size:
            groups: []
        file:
            groups: []
        url:
            groups: []