Acted\LegalDocsBundle\Entity\EventOffer:
    exclusion_policy: NONE
    properties:
        status:
            groups: [Default, getEvent]
        event:
            groups: [Default, getEvent]
        event:
            groups: [Default, getEvent]