Acted\LegalDocsBundle\Entity\Offer:
    exclusion_policy: NONE
    properties:
        performances:
            groups: [chat_list, chat_room]
        comments:
            groups: [chat_list, chat_room]

