Acted\LegalDocsBundle\Entity\RefCity:
    exclusion_policy: NONE
    properties:
        region:
            exclude: true
        name:
            groups: [Default, getEvent, chat_list, all_messages, chat_room]
        id:
            groups: [Default, getEvent, chat_room]
        latitude:
            groups: [chat_room]
        longitude:
            groups: [chat_room]
