Acted\LegalDocsBundle\Entity\Media:
  exclusion_policy: NONE
  properties:
    performances:
      exclude: true
    link:
      groups: [Default, block]
    thumbnail:
      groups: [Default, block]
    mediaType:
      groups: [Default, block]