Acted\LegalDocsBundle\Entity\Profile:
    exclusion_policy: NONE
    properties:
        user:
            groups: [getEvent]
        performances:
            groups: []
        services:
            groups: []
    virtual_properties:
        getPerformances:
          serialized_name: performances
          groups: [order]
        getServices:
          serialized_name: services
          groups: [order]