Acted\LegalDocsBundle\Entity\ChatRoom:
    exclusion_policy: NONE
    properties:
        id:
            groups: [chat_list]
        event:
            groups: [chat_list, chat_room]
        offer:
            groups: [chat_list, chat_room]
        message:
            groups: [chat_room]
    virtual_properties:
        getLastMessage:
            groups: [chat_list]
