Acted\LegalDocsBundle\Entity\Artist:
  exclusion_policy: NONE
  custom_accessor_order: [name, slug, rating]
  properties:
    id:
      groups: [recommend_artist]
    name:
      groups: [Default, block, quote_request, recommend_artist]
    slug:
      groups: [Default, block, quote_request, recommend_artist]
    user:
      groups: [quote_request]
    recommend:
      groups: [recommend_artist]
  virtual_properties:
    getCityName:
      serialized_name: city
      groups: [Default, block]
    getCountryName:
      serialized_name: country
      groups: [Default, block]
    getRating:
      serialized_name: rating
      groups: [Default, block]
    getVotesCount:
      serialized_name: votes_count
      groups: [block]
    getCategoriesNames:
      serialized_name: categories
      groups: [block, quote_request]
    getLastPerformanceMedia:
      serialized_name: media
      groups: [block]
    getAllPerformance:
      serialized_name: allPerformance
      groups: [quote_request]