Acted\LegalDocsBundle\Entity\ChatRoom:
    exclusion_policy: NONE
    properties:
        id:
            groups: [chat_list, all_messages, chat_room]
            serialized_name: chat_id
        event:
            groups: [chat_room, chat_list, all_messages]
        offer:
            groups: [chat_list, chat_room, all_messages]
        message:
            groups: [chat_room]
    virtual_properties:
        getLastMessage:
            groups: [chat_list]
