Acted\LegalDocsBundle\Entity\Profile:
    exclusion_policy: NONE
    properties:
        user:
            groups: [getEvent]
    virtual_properties:
        getExistedPerformances:
          serialized_name: performances
          groups: [order]
        getExistedServices:
          serialized_name: services
          groups: [order]