Acted\LegalDocsBundle\Entity\Event:
    exclusion_policy: NONE
    properties:
        id:
            groups: [chat_list, getEvent, enquiries, messages_feedbacks, all_messages, order]
        city:
            groups: [Default, getEvent, chat_list, chat_room, all_messages]
        eventRef:
            groups: [Default, getEvent]
        eventTypeId:
            groups: [Default, getEvent, chat_list, chat_room]
        venueTypeId:
            groups: [Default, getEvent]
        startingDate:
            groups: [Default, getEvent, chat_list, chat_room, all_messages, order]
        endingDate:
            groups: [Default, getEvent, order]
        timing:
            groups: [Default, getEvent, chat_list, chat_room, order]
        comments:
            groups: [Default, getEvent, chat_list, chat_room, order]
        numberOfGuests:
            groups: [getEvent, chat_room, order]
        venueType:
            groups: [getEvent, chat_room, order]
        eventType:
            groups: [getEvent, chat_room, order]
        title:
            groups: [Default, getEvent, chat_list, chat_room, all_messages, order]
        address:
            groups: [Default, getEvent, chat_list, chat_room, order]
            serialized_name: location
        user:
            groups: [chat_list, getEvent, messages_feedbacks]
        requestQuotations:
            groups: [chat_room]
        eventOffer:
          groups: [getEvent]
        countDays:
          groups: [getEvent, order]
    virtual_properties:
        getCountryId:
            serialized_name: countryId
            groups: [getEvent]
        getCountryName:
            serialized_name: countryName
            groups: [chat_room]
