Acted\LegalDocsBundle\Entity\Package:
  properties:
    id:
      groups: [order]
    name:
      groups: [order]
    options:
      groups: []
  virtual_properties:
      getExistedOptions:
        serialized_name: options
        groups: [order]