Acted\LegalDocsBundle\Entity\RequestQuotation:
    exclusion_policy: NONE
    properties:
        status:
            groups: [enquiries]
        isOutdated:
            groups: []
        event:
            groups: [enquiries]
    virtual_properties:
        getEvent:
            serialized_name: event
            groups: []
