Acted\LegalDocsBundle\Entity\User:
  exclusion_policy: NONE
  properties:
    passwordHash:
      exclude: true
    confirmationToken:
      exclude: true
    roles:
      exclude: true
    avatar:
      groups: [quote_request, chat_room, message, all_messages]
    firstname:
      groups: [chat_list, chat_room, message, all_messages]
    lastname:
      groups: [chat_list, chat_room, message, all_messages]
  virtual_properties:
      getRoles:
        serialized_name: roles
        type: array<string>
      getRoleName:
        serialized_name: role_name
        groups: [chat_list, chat_room, message, all_messages]