Acted\LegalDocsBundle\Entity\EventOffer:
    exclusion_policy: NONE
    properties:
        status:
            groups: [Default, getEvent, all_messages, chat_list]
        event:
            groups: [Default, getEvent]
        offer:
            groups: [getEvent]