Acted\LegalDocsBundle\Entity\User:
  exclusion_policy: NONE
  properties:
    id:
      groups: [getEvent, users_list, recommend_artist, spotlight_artist]
    passwordHash:
      exclude: true
    confirmationToken:
      exclude: true
    roles:
      exclude: true
    avatar:
      groups: [quote_request, chat_room, message, all_messages, profile_settings, messages_feedbacks]
    firstname:
      groups: [order, chat_list, chat_room, message, all_messages, users_list, profile_settings, getEvent, messages_feedbacks]
    lastname:
      groups: [order, chat_list, chat_room, message, all_messages, users_list, profile_settings, getEvent, messages_feedbacks]
    active:
      groups: [users_list]
    fake:
      groups: [users_list]
    artist:
      groups: [users_list]
    postcode:
      groups: [profile_settings]
    email:
      groups: [profile_settings]
    primaryPhone:
      groups: [profile_settings]
    profile:
      groups: [order]
  virtual_properties:
      getUserEmail:
        serialized_name: email
        groups: [users_list]
      getRoles:
        serialized_name: roles
        type: array<string>
      getRoleName:
        serialized_name: role_name
        groups: [chat_list, chat_room, message, all_messages, users_list]
      getProfilePaymentSetting:
        serialized_name: payment_settings
        groups: [profile_settings]
