Acted\LegalDocsBundle\Entity\Performance:
    exclusion_policy: NONE
    properties:
        id:
            groups: [order, chat_list, chat_room, all_messages, performance_create]
        title:
            groups: [order, chat_list, chat_room, all_messages]
        status:
            groups: [performance_create, order]
        profile:
            groups: [getEvent]
        isVisible:
          groups: [order]
        type:
          groups: [order]
        packages:
          groups: []
        deletedTime:
          groups: [order]
    virtual_properties:
        getExistedPackages:
          serialized_name: packages
          groups: [order]