Acted\LegalDocsBundle\Entity\User:
  exclusion_policy: NONE
  properties:
    passwordHash:
      exclude: true
    confirmationToken:
      exclude: true
    roles:
      exclude: true
    avatar:
      groups: [quote_request, chat_room]
    firstname:
      groups: [chat_list, chat_room]
    lastname:
      groups: [chat_list, chat_room]
  virtual_properties:
      getRoles:
        serialized_name: roles
        type: array<string>