Acted\LegalDocsBundle\Entity\OrderItem:
  properties:
    id:
      groups: [order]

    data:
      groups: [order, chat_room]

  virtual_properties:
    getSelectedOptions:
      serialized_name: selected_options
      groups: [chat_room, order]

    getOptions:
      serialized_name: options
      groups: [chat_room, order]