Acted\LegalDocsBundle\Entity\RefCity:
    exclusion_policy: NONE
    properties:
        region:
            exclude: true
        name:
            groups: [Default, getEvent, chat_list]
        id:
            groups: [Default, getEvent]
