Acted\LegalDocsBundle\Entity\Artist:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 3
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: slug