Acted\LegalDocsBundle\Entity\User:
  properties:
    lastname:
      - NotBlank: ~
      - Length:
          min: 3
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email