<?php

namespace Acted\LegalDocsBundle\Repository;
use Acted\LegalDocsBundle\Entity\Artist;

/**
 * ArtistRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByArtistQuery(Artist $artist)
    {
        return $this->createQueryBuilder('r')
            ->where('r.artist = :artist')
            ->setParameter('artist', $artist)
            ->getQuery();
    }
}
