<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * ArtistAgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistAgendaRepository extends \Doctrine\ORM\EntityRepository
{
}
