<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * ArtistRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
