<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynArtistAgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynArtistAgendaRepository extends \Doctrine\ORM\EntityRepository
{
}
