<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynArtistRepository extends \Doctrine\ORM\EntityRepository
{
}
