<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynArtistRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynArtistRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
