<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynClientRepository extends \Doctrine\ORM\EntityRepository
{
}
