<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
