<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynEventServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynEventServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
