<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynEventOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynEventOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
