<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynEventRepository extends \Doctrine\ORM\EntityRepository
{
}
