<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynEventExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynEventExtraRepository extends \Doctrine\ORM\EntityRepository
{
}
