<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynMessageFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynMessageFileRepository extends \Doctrine\ORM\EntityRepository
{
}
