<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
