<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
