<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
