<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynProfileMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynProfileMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
