<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
