<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynPerformanceMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynPerformanceMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
