<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynPerformanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynPerformanceRepository extends \Doctrine\ORM\EntityRepository
{
}
