<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
