<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynStaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynStaffRepository extends \Doctrine\ORM\EntityRepository
{
}
