<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * DynUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynUserRepository extends \Doctrine\ORM\EntityRepository
{
}
