<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * EventServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
