<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * EventExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventExtraRepository extends \Doctrine\ORM\EntityRepository
{
}
