<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * HomespotlightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomespotlightRepository extends \Doctrine\ORM\EntityRepository
{
}
