<?php

namespace Acted\LegalDocsBundle\Repository;
use Acted\LegalDocsBundle\Entity\Profile;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLastVideoMedia(Profile $profile)
    {
        return $this->createQueryBuilder('m')
            ->innerJoin('m.performances', 'p')
            ->where('m.mediaType = :mediaType')
            ->setParameter('mediaType', 'video')
            ->andWhere('p.profile = :profile')
            ->setParameter('profile', $profile)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
