<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * MessageFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageFileRepository extends \Doctrine\ORM\EntityRepository
{
}
