<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $userId
     * @param string $filter
     * @return array
     */
    public function getAllMessages($userId, $filter=null)
    {
        $query = $this->createQueryBuilder('m')
            ->where('m.receiverUser = :userId')
            ->setParameter('userId', $userId);

        if ($filter) {
            switch ($filter){
                case 'archived':
                    $query
                        ->andWhere('m.archived = :archived')
                        ->setParameter('archived', true)
                    ;
                    break;
                case 'unread':
                    $query
                        ->andWhere('m.readDateTime IS null')
                    ;
                    break;
                default:
                    break;
            }
        }


        return $query->getQuery()->getResult();
    }
}
