<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllMessages($userId)
    {
        return $this->createQueryBuilder('m')
            ->where('m.receiverUser = :userId')
            ->setParameter('userId', $userId)
            ->getQuery()->getResult();
    }
}
