<?php

namespace Acted\LegalDocsBundle\Repository;
use Acted\LegalDocsBundle\Entity\Artist;
use Symfony\Component\VarDumper\VarDumper;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByArtistQuery(Artist $artist)
    {
        return $this->createQueryBuilder('o')
            ->innerJoin('o.performance', 'p')
            ->innerJoin('p.profile', 'pr')
            ->innerJoin('pr.user', 'u')
            ->innerJoin('u.artist', 'a')
            ->where('a = :artist')
            ->setParameter('artist', $artist)
            ->getQuery();
    }

    /**
     * @param User $artist
     * @return int
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function countOffersForArtist($artist)
    {
        $query = $this->createQueryBuilder('o')
            ->select('COUNT(o.id) as amount')
            ->leftJoin('o.performances', 'p')
            ->where('p.profile = :user')
            ->setParameter('user', $artist)
        ;

        return $query->getQuery()->getOneOrNullResult();
    }

}
