<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * OptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeOptions($ids)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $date = date("Y-m-d H:i:s");
        $params = array('deletedTime' => $date, 'optionIds' => $ids);

        $whereCriteria = 'opt.deletedTime IS NULL AND opt.id IN (:optionIds)';

        $qb->update('ActedLegalDocsBundle:Option', 'opt')
            ->set('opt.deletedTime', ':deletedTime')
            ->where($whereCriteria)
            ->setParameters($params);

        $qb->setParameters($params);

        $qb->getQuery()->execute();
    }

    public function getOptionIdsByPackageIds($ids)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $params = array('packageIds' => $ids);

        $whereCriteria = 'opt.deletedTime IS NULL AND opt.package IN (:packageIds)';
        $date = date("Y-m-d H:i:s");

        $qb->from('ActedLegalDocsBundle:Option', 'opt');
        $qb->select('opt.id');
        $qb->where($whereCriteria);
        $qb->setParameters($params);

        $optionIds = $qb->getQuery()->getResult();

        foreach($optionIds as $key => $value) {
            $optionIds[$key] = $value['id'];
        }

        return $optionIds;
    }
}
