<?php

namespace Acted\LegalDocsBundle\Repository;
use Acted\LegalDocsBundle\Entity\OrderItem;
use Acted\LegalDocsBundle\Entity\OrderItemPerformance;
use Acted\LegalDocsBundle\Entity\OrderItemService;
use Acted\LegalDocsBundle\Entity\Performance;
use Acted\LegalDocsBundle\Entity\Service;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{

}
