<?php

namespace Acted\LegalDocsBundle\Repository;
use Acted\LegalDocsBundle\Entity\OrderItem;
use Acted\LegalDocsBundle\Entity\OrderItemPerformance;
use Acted\LegalDocsBundle\Entity\OrderItemService;
use Acted\LegalDocsBundle\Entity\Performance;
use Acted\LegalDocsBundle\Entity\Service;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * OrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param Service $service
     * @return OrderItem
     */
    public function createItemForService(Service $service){
        $serviceItem = new OrderItemService();
        $serviceItem->setService($service);
        return $serviceItem;
    }


    /**
     * @param Performance $performance
     * @return OrderItem
     */
    public function createItemForPerformance(Performance $performance){
        $perfItem = new OrderItemPerformance();
        $perfItem->setPerformance($performance);
        return $perfItem;
    }

}
