<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * PaymentSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
