<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * PerformanceMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerformanceMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
