<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * PriceOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceOptionRateRepository extends \Doctrine\ORM\EntityRepository
{
}
