<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * PricePackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricePackageRepository extends \Doctrine\ORM\EntityRepository
{
}
