<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * ProfileMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
