<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * QuotationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
