<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RecommendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommendRepository extends \Doctrine\ORM\EntityRepository
{
}
