<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RefCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
