<?php

namespace Acted\LegalDocsBundle\Repository;
use Acted\LegalDocsBundle\Entity\RefCountry;

/**
 * RefCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefCityRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByCountry(RefCountry $country)
    {
        return $this->createQueryBuilder('c')
            ->join('c.region', 'r')
//            ->join('r.country', 'country')
            ->where('r.country = :country')
            ->setParameter('country', $country)
            ->getQuery()
            ->getResult();
    }

}
