<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RefCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefCityRepository extends \Doctrine\ORM\EntityRepository
{
}
