<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RefCurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefCurrencyRepository extends \Doctrine\ORM\EntityRepository
{
}
