<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RefEventTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefEventTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
