<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RefPaymentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefPaymentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
