<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RefRightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefRightRepository extends \Doctrine\ORM\EntityRepository
{
}
