<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RefRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
