<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RefRoleRightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefRoleRightRepository extends \Doctrine\ORM\EntityRepository
{
}
