<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RefRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
