<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RefTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
