<?php

namespace Acted\LegalDocsBundle\Repository;

/**
 * RefVenueTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefVenueTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
