<?php

namespace Acted\LegalDocsBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Acted\LegalDocsBundle\Entity\RequestQuotation;
use Acted\LegalDocsBundle\Entity\ServiceRequestQuotation;
use Acted\LegalDocsBundle\Entity\Service;
use Acted\LegalDocsBundle\Entity\Package;
use Acted\LegalDocsBundle\Entity\Price;
use Acted\LegalDocsBundle\Entity\Option;
use Acted\LegalDocsBundle\Entity\Rate;

/**
 * ServiceRequestQuotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRequestQuotationRepository extends EntityRepository
{
    /**
     * Get serviceRequestQuotations by request id
     * @param $requestId
     * @return array
     */
    public function getServiceRequestQuotations($requestId)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $params = array('requestId' => $requestId);

        $qb->from('ActedLegalDocsBundle:ServiceRequestQuotation', 'ser_rq');
        $qb->select('ser_rq, ser, pac, opt, rate, price');
        $qb->leftJoin('ser_rq.service', 'ser', 'WITH', 'ser.deletedTime IS NULL');
        $qb->leftJoin('ser.packages', 'pac', 'WITH', 'pac.deletedTime IS NULL');
        $qb->leftJoin('pac.options', 'opt', 'WITH', 'opt.deletedTime IS NULL');
        $qb->leftJoin('opt.rates', 'rate', 'WITH', 'rate.deletedTime IS NULL');
        $qb->leftJoin('rate.price', 'price');
        $qb->where('ser_rq.requestQuotation = :requestId');
        $qb->setParameters($params);

        return $qb->getQuery()->getArrayResult();
    }

    public function getDraftServiceRequestQuotations($requestId)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $params = array('requestId' => $requestId);

        $qb->from('ActedLegalDocsBundle:ServiceRequestQuotation', 'ser_rq');
        $qb->select('ser_rq, ser, pac, opt, rate, price');
        $qb->leftJoin('ser_rq.service', 'ser');
        $qb->leftJoin('ser.packages', 'pac');
        $qb->leftJoin('pac.options', 'opt');
        $qb->leftJoin('opt.rates', 'rate');
        $qb->leftJoin('rate.price', 'price');
        $qb->where('ser_rq.requestQuotation = :requestId');
        $qb->setParameters($params);

        return $qb->getQuery()->getArrayResult();
    }

    public function getRelatedServiceIds($serviceRequestQuotations)
    {
        $serviceIds = array();
        $packageIds = array();
        $optionIds = array();
        $rateIds = array();
        $priceIds = array();

        foreach ($serviceRequestQuotations as $serviceRequestQuotation) {
            if (empty($serviceRequestQuotation['service'])) {
                continue;
            }

            $service = $serviceRequestQuotation['service'];
            $serviceIds[] = $service['id'];

            foreach ($service['packages'] as $package) {
                $packageIds[] = $package['id'];
                foreach ($package['options'] as $option) {
                    $optionIds[] = $option['id'];
                    foreach ($option['rates'] as $rate) {
                        $rateIds[] =  $rate['id'];
                        $priceIds[] = $rate['price']['id'];
                    }
                }
            }
        }

        return array(
            'serviceIds' => $serviceIds,
            'packageIds' => $packageIds,
            'optionIds' => $optionIds,
            'rateIds' => $rateIds,
            'priceIds' => $priceIds
        );
    }

    public function getServiceRequestQuotationsByProfileId($profileId)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $params = array('profileId' => $profileId);

        $qb->from('ActedLegalDocsBundle:Service', 'ser');
        $qb->select('ser, pac, opt, rate, price');
        $qb->leftJoin('ser.packages', 'pac', 'WITH', 'pac.deletedTime IS NULL');
        $qb->leftJoin('pac.options', 'opt', 'WITH', 'opt.deletedTime IS NULL');
        $qb->leftJoin('opt.rates', 'rate', 'WITH', 'rate.deletedTime IS NULL');
        $qb->leftJoin('rate.price', 'price');
        $qb->where('ser.deletedTime IS NULL AND ser.profile = :profileId');
        $qb->setParameters($params);

        return $qb->getQuery()->getResult();
    }

    public function changeServiceSelected($requestId, $serviceId)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $params = array('requestId' => $requestId, 'serviceId' => $serviceId);

        $whereCriteria = 'ser_rq.requestQuotation IN (:requestId) AND ser_rq.service IN (:serviceId)';

        $qb->update('ActedLegalDocsBundle:ServiceRequestQuotation', 'ser_rq')
            ->set('ser_rq.isSelected', '1-ser_rq.isSelected')
            ->where($whereCriteria)
            ->setParameters($params);

        return $qb->getQuery()->execute();
    }

    public function copyServiceRequestQuotation($serviceRequestQuotations, $profile, $requestQuotation)
    {
        $em = $this->getEntityManager();

        $serviceIds = array();
        $packageIds = array();
        $optionIds = array();
        $rateIds = array();
        $priceIds = array();

        foreach ($serviceRequestQuotations as $serviceRequestQuotation) {

            if (empty($serviceRequestQuotation['service']) && !isset($serviceRequestQuotation['packages'])) {
                continue;
            }

            if (empty($serviceRequestQuotation['service']) && isset($serviceRequestQuotation['packages'])) {
                $service = $serviceRequestQuotation;
                $isSelected = false;
            } else {
                $service = $serviceRequestQuotation['service'];
                $isSelected = $serviceRequestQuotation['isSelected'];
            }

            $serviceIds[] = $service['id'];
            $copiedService = new Service();

            $copiedService->setTitle($service['title']);
            $copiedService->setIsQuotation(true);
            $copiedService->setProfile($profile);
            $copiedService->setIsVisible($service['isVisible']);
            $em->persist($copiedService);

            /*Connect services to request*/
            $serviceRequestQuotation = new ServiceRequestQuotation();
            $serviceRequestQuotation->setService($copiedService);
            $serviceRequestQuotation->setRequestQuotation($requestQuotation);
            $serviceRequestQuotation->setIsSelected($isSelected);
            $em->persist($serviceRequestQuotation);

            foreach ($service['packages'] as $package) {

                $packageIds[] = $package['id'];

                $copiedPackage = new Package();
                $copiedPackage->setProfile($profile);
                $copiedPackage->setService($copiedService);
                $copiedPackage->setName($package['name']);
                $em->persist($copiedPackage);

                foreach ($package['options'] as $option) {

                    $optionIds[] = $option['id'];

                    $copiedOption = new Option();
                    $copiedOption->setPackage($copiedPackage);
                    $copiedOption->setDuration($option['duration']);
                    $copiedOption->setQty($option['qty']);
                    $copiedOption->setPriceOnRequest($option['priceOnRequest']);
                    $em->persist($copiedOption);

                    foreach ($option['rates'] as $rate) {
                        $rateIds[] =  $rate['id'];

                        $price = new Price();
                        $price->setAmount($rate['price']['amount']);
                        $em->persist($price);

                        $priceIds[] = $rate['price']['id'];

                        $copiedRate = new Rate();
                        $copiedRate->setOption($copiedOption);
                        $copiedRate->setPrice($price);
                        $em->persist($copiedRate);
                    }
                }
            }
        }


        $em->flush();

        return array(
            'serviceIds' => $serviceIds,
            'packageIds' => $packageIds,
            'optionIds' => $optionIds,
            'rateIds' => $rateIds,
            'priceIds' => $priceIds
        );
    }
}